### ISSUE TITLE
[Rust 1.65.0] Critical error in --release build: remove() with an exist key returns None

### ISSUE THREAD

**Issue by zitsen** [wvwwvwwv/scalable-concurrent-containers#84] opened 2022-11-16 03:35 UTC
I say release build because it's correct in debug build.

**Comment by wvwwvwwv** [comment] 2022-11-16 03:45
Thanks for reporting the issue!

Would you please elaborate on the symptom a little bit further?

I need to know,

1. The type of the data structure. I assume that you're talking about `HashMap`, but need to be sure about it.
2. A possible reproducible scenario. E.g., parallel insert/remove? or single-threaded insert/remove?
3. The crate version that you use.
4. Criticality. The whole source code is not part of my job, and it's a kind of my free-time activity, so I might not be able to prioritize debugging of the issue unless it's very critical.

**Comment by wvwwvwwv** [comment] 2022-11-16 05:53
Hi @zitsen 

There was a problem with SCC 0.8.x with the `retain_*` methods; https://github.com/wvwwvwwv/scalable-concurrent-containers/issues/77.

Could you try SCC 0.11.x instead?

**Comment by wvwwvwwv** [comment] 2022-11-16 12:32
Acknowledged the problem; looks like something's been changed in Rust 1.65.0. I'll try to fix it as soon as possible.

**Comment by wvwwvwwv** [comment] 2022-11-17 05:57
`MaybeUninit` handling has changed since Rust 1.65.0 - fixed it. After cleaning up the code, I'll upload SCC 0.11.3.

**Comment by wvwwvwwv** [comment] 2022-11-17 07:07
I admit that it was a touch bug. Anyway, fixed in SCC 0.11.3, @zitsen thanks for reporting this bug!

**Closed by wvwwvwwv** 2022-11-17 07:07 UTC
Labels: bug
